url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "pragmaticbrands.de"
lang: "de"
sass:
    style: compressed
    silence_deprecations:
        - import
